import { useCallback,useEffect,useState } from 'react'
import { apiRequest,type ApiUser } from './api'
import type { ActivityEntry } from './activityLog'
import { X,Users,Activity,ShieldCheck,Trash2,Search,UserCheck } from 'lucide-react'
type Group={id:string;name:string;description:string}
type Overview={online:Array<{email:string;name:string;lastSeen:string}>;totalUsers:number;totalGroups:number;totalLogs:number}
export default function AdminPage({onClose}:{onClose:()=>void}){
 const [overview,setOverview]=useState<Overview|null>(null),[users,setUsers]=useState<ApiUser[]>([]),[groups,setGroups]=useState<Group[]>([]),[logs,setLogs]=useState<ActivityEntry[]>([])
 const [email,setEmail]=useState(''),[groupName,setGroupName]=useState(''),[q,setQ]=useState(''),[level,setLevel]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('')
 const load=useCallback(async()=>{const [o,u,g]=await Promise.all([apiRequest<Overview>('/api/admin/overview'),apiRequest<ApiUser[]>('/api/admin/users'),apiRequest<Group[]>('/api/admin/groups')]);setOverview(o);setUsers(u);setGroups(g)},[])
 const loadLogs=useCallback(async()=>{const params=new URLSearchParams({q,level});setLogs(await apiRequest<ActivityEntry[]>(`/api/admin/logs?${params}`))},[q,level])
 useEffect(()=>{const initial=setTimeout(()=>{void load();void loadLogs()},0),timer=setInterval(()=>void load(),30000);return()=>{clearTimeout(initial);clearInterval(timer)}},[load,loadLogs])
 const addUser=async()=>{if(!email)return;await apiRequest('/api/admin/users',{method:'POST',body:JSON.stringify({email,active:true,role:'user'})});setEmail('');load()}
 const patchUser=async(user:ApiUser,patch:Partial<ApiUser>)=>{await apiRequest(`/api/admin/users/${user.id}`,{method:'PATCH',body:JSON.stringify(patch)});load()}
 const addGroup=async()=>{if(!groupName)return;await apiRequest('/api/admin/groups',{method:'POST',body:JSON.stringify({name:groupName})});setGroupName('');load()}
 const clearLogs=async()=>{if(!from||!to)return alert('Chọn thời gian bắt đầu và kết thúc.');if(!confirm('Xóa vĩnh viễn log trong khoảng thời gian đã chọn?'))return;await apiRequest('/api/admin/logs',{method:'DELETE',body:JSON.stringify({from:new Date(from).toISOString(),to:new Date(to).toISOString()})});load();loadLogs()}
 return <div className="admin-page"><header><span><ShieldCheck/>PACE PDF Administration</span><button onClick={onClose}><X/></button></header>
 <div className="admin-stats"><article><UserCheck/><b>{overview?.online.length||0}</b><span>Đang online</span></article><article><Users/><b>{overview?.totalUsers||0}</b><span>Users</span></article><article><ShieldCheck/><b>{overview?.totalGroups||0}</b><span>Groups</span></article><article><Activity/><b>{overview?.totalLogs||0}</b><span>Activity logs</span></article></div>
 <main><section><h2>User được phép đăng nhập</h2><div className="admin-add"><input placeholder="email@pace.edu.vn" value={email} onChange={e=>setEmail(e.target.value)}/><button onClick={addUser}>Thêm user</button></div><div className="admin-table">{users.map(user=><div key={user.id}><b>{user.email}</b><select value={user.role} onChange={e=>patchUser(user,{role:e.target.value as ApiUser['role']})}><option value="user">User</option><option value="admin">Admin</option></select><label><input type="checkbox" checked={user.active} onChange={e=>patchUser(user,{active:e.target.checked})}/> Active</label><select multiple value={user.groupIds} onChange={e=>patchUser(user,{groupIds:Array.from(e.target.selectedOptions,x=>x.value)})}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></div>)}</div></section>
 <section><h2>Quản lý group</h2><div className="admin-add"><input placeholder="Tên group" value={groupName} onChange={e=>setGroupName(e.target.value)}/><button onClick={addGroup}>Tạo group</button></div><div className="group-list">{groups.map(g=><span key={g.id}>{g.name}<button onClick={async()=>{if(confirm(`Xóa group ${g.name}?`)){await apiRequest(`/api/admin/groups/${g.id}`,{method:'DELETE'});load()}}}>×</button></span>)}</div><h3>User online</h3>{overview?.online.map(x=><p key={x.email}>{x.name} · {x.email} · {new Date(x.lastSeen).toLocaleTimeString('vi-VN')}</p>)}</section>
 <section className="admin-logs"><h2>Activity logs</h2><div className="log-tools"><label><Search/><input placeholder="Search action, email, metadata…" value={q} onChange={e=>setQ(e.target.value)}/></label><select value={level} onChange={e=>setLevel(e.target.value)}><option value="">Tất cả level</option><option>info</option><option>success</option><option>warning</option><option>security</option></select><button onClick={loadLogs}>Tìm kiếm</button><input type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/><input type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/><button className="danger" onClick={clearLogs}><Trash2/>Clear theo thời gian</button></div><div className="log-table">{logs.map(log=><div key={log.id}><time>{new Date(log.timestamp).toLocaleString('vi-VN')}</time><b>{(log as ActivityEntry&{userEmail?:string}).userEmail||log.userName}</b><code>{log.action}</code><span>{log.description}</span></div>)}</div></section></main></div>
}
