import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './styles.css'
import './auth-styles.css'
import './pace-theme.css'
import './pace-fixes.css'
import './ocr-styles.css'
import './text-format.css'
import './brand-fixes.css'
import './document-tools.css'
import './inline-text-editor.css'
import './admin.css'
import '@fontsource/be-vietnam-pro/latin-400.css'
import '@fontsource/be-vietnam-pro/vietnamese-400.css'
import '@fontsource/be-vietnam-pro/latin-400-italic.css'
import '@fontsource/be-vietnam-pro/vietnamese-400-italic.css'
import '@fontsource/be-vietnam-pro/latin-700.css'
import '@fontsource/be-vietnam-pro/vietnamese-700.css'
import '@fontsource/be-vietnam-pro/latin-700-italic.css'
import '@fontsource/be-vietnam-pro/vietnamese-700-italic.css'
import '@fontsource/arimo/latin-400.css'
import '@fontsource/arimo/vietnamese-400.css'
import '@fontsource/arimo/latin-400-italic.css'
import '@fontsource/arimo/vietnamese-400-italic.css'
import '@fontsource/arimo/latin-700.css'
import '@fontsource/arimo/vietnamese-700.css'
import '@fontsource/arimo/latin-700-italic.css'
import '@fontsource/arimo/vietnamese-700-italic.css'
import '@fontsource/noto-sans/latin-400.css'
import '@fontsource/noto-sans/vietnamese-400.css'
import '@fontsource/noto-sans/latin-400-italic.css'
import '@fontsource/noto-sans/vietnamese-400-italic.css'
import '@fontsource/noto-sans/latin-700.css'
import '@fontsource/noto-sans/vietnamese-700.css'
import '@fontsource/noto-sans/latin-700-italic.css'
import '@fontsource/noto-sans/vietnamese-700-italic.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode><App /></StrictMode>,
)
